services:
  web:
    build: .
    container_name: mybustimes-tracking
    command: >
      gunicorn mybustimes.wsgi:application
      --workers 2
      --max-requests 200
      --max-requests-jitter 50
      --bind 0.0.0.0:8000
      --log-level info
    env_file: mybustimes/.env
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    mem_limit: 2g
    mem_reservation: 1g

  redis:
    image: 'redis:7-alpine'
    container_name: redis-mbt
    restart: unless-stopped
    mem_limit: 256m

  db:
    image: 'postgres:16'
    container_name: postgres-db-mbt
    restart: unless-stopped
    environment:
      POSTGRES_DB: mybustimes
      POSTGRES_USER: mybustimesDBuser
      POSTGRES_PASSWORD: CHANGE-ME-DO-NOT-KEEP-THIS
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    mem_limit: 2g

volumes:
  postgres-data:
