# Generated by Django 5.2.14 on 2026-06-16 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_name', models.CharField(max_length=100)),
                ('board_type', models.CharField(choices=[('duty', 'Duty'), ('running-boards', 'Running Board')], default='duty', max_length=20)),
                ('duty_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='fleet.mbtoperator')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('route_num', models.CharField(blank=True, max_length=255, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inbound_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('outbound_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('other_destination', models.JSONField(blank=True, null=True)),
                ('route_operators', models.ManyToManyField(related_name='route_other_operators', to='fleet.mbtoperator')),
            ],
        ),
        migrations.CreateModel(
            name='routeStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=True)),
                ('circular', models.BooleanField(default=False)),
                ('stops', models.JSONField()),
                ('snapped_route', models.TextField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
