# Generated by Django 5.2.14 on 2026-06-16 02:35

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fleet',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('fleet_number', models.CharField(blank=True, db_index=True, null=True)),
                ('reg', models.CharField(blank=True, db_index=True, null=True)),
                ('colour', models.CharField(blank=True, db_index=True)),
                ('in_service', models.BooleanField(db_index=True, default=True)),
                ('sim_lat', models.FloatField(blank=True, null=True)),
                ('sim_lon', models.FloatField(blank=True, null=True)),
                ('sim_heading', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(unique=True)),
                ('order_by', models.CharField(choices=[('fleet_number', 'Fleet Number'), ('operator_name', 'Operator Name')], default='fleet_number', max_length=20)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='liverie',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('colour', models.CharField(max_length=100)),
                ('left_css', models.TextField(blank=True, max_length=2048, verbose_name='Left CSS')),
                ('right_css', models.TextField(blank=True, max_length=2048, verbose_name='Right CSS')),
                ('text_colour', models.CharField(blank=True, max_length=100)),
                ('stroke_colour', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'liveries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='mapTileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tile_url', models.CharField(max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Map Tile Sets',
            },
        ),
        migrations.CreateModel(
            name='MBTOperator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(unique=True)),
                ('operator_code', models.CharField(unique=True)),
                ('operator_slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('operator_details', models.JSONField(blank=True, default=fleet.models.default_operator_details, null=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('show_trip_id', models.BooleanField(default=True)),
                ('vehicles_for_sale', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('public_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('double_decker', models.BooleanField(default=False)),
                ('lengths', models.TextField(blank=True)),
                ('type', models.CharField(default='Bus')),
                ('fuel', models.CharField(default='Diesel')),
            ],
        ),
    ]
