# Generated by Django 5.2.14 on 2026-06-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('main', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='current_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_current_trip', to='tracking.trip'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liverie',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livery_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liverie',
            name='aproved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livery_aproved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleet',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.liverie'),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.group'),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='mapTile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='fleet.maptileset'),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='region',
            field=models.ManyToManyField(related_name='operators', to='main.region'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_operator', to='fleet.mbtoperator'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.organisation'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='aproved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_aproved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleet',
            name='vehicleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicletype'),
        ),
    ]
