# Generated by Django 5.2.14 on 2026-06-16 02:35

import django.db.models.deletion
import tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('trip_display_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_route_num', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_end_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('trip_ended', models.BooleanField(db_index=True, default=False)),
                ('trip_missed', models.BooleanField(db_index=True, default=False)),
                ('trip_inbound', models.BooleanField(blank=True, db_index=True, null=True)),
                ('trip_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.duty')),
                ('trip_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('trip_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('tracking_data', models.JSONField(default=tracking.models.default_tracking_data)),
                ('tracking_history_data', models.JSONField(default=tracking.models.default_tracking_history)),
                ('tracking_start_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tracking_end_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tracking_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tracking_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tracking_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('trip_ended', models.BooleanField(db_index=True, default=False)),
                ('tracking_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('tracking_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
                ('tracking_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip_ended'], name='tracking_tr_trip_en_1a75f4_idx'), models.Index(fields=['tracking_start_at'], name='tracking_tr_trackin_c0c4fc_idx'), models.Index(fields=['tracking_vehicle'], name='tracking_tr_trackin_8383df_idx'), models.Index(fields=['tracking_route'], name='tracking_tr_trackin_f0867a_idx')],
            },
        ),
    ]
